name: Deploy Frontend

on:
  push:
    branches: [feature_test]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo bash -c '
            cd /root/vehicle_client
            git pull origin feature_test
            /root/.nvm/versions/node/v22.14.0/bin/pnpm install
            /root/.nvm/versions/node/v22.14.0/bin/pnpm build
            rm -rf /var/www/vehicle/*
            cp -r dist/* /var/www/vehicle/
            systemctl reload nginx
            '
